const qs=new URLSearchParams(location.search);const headId=qs.get('headId')||'';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let selected=null;let DATA={};
function labelHead(h){return [h.OEM,h.Model,(h.Variant&&h.Variant!=='Standard'?h.Variant:''),h.ReleaseYear].filter(Boolean).join(' ')}
function materialGroup(v){return v==='Steel'?'Steel':v==='Graphite'?'Graphite':'Other / Material TBD'}
function list(v){return Array.isArray(v)&&v.length?v.join(', '):'—'}
function torque(d){if(d.torqueMin===''&&d.torqueMax==='')return '—';if(d.torqueMin===d.torqueMax)return String(d.torqueMin);return `${d.torqueMin}–${d.torqueMax}`}
function familyName(fid,f){return f?.FamilyName||fid.split('|').slice(-1)[0]||fid}
function cardHtml(r){const f=DATA.families[r.ShaftFamilyID]||{};const d=DATA.details[r.ShaftFamilyID];const mpf=r.MPFCode?`<div class="mpf"><b>MPF:</b> ${esc(r.MPFCode)}</div>`:'';let details='';if(d){details=`<div class="family-detail"><div><b>Weights</b>${esc(list(d.weights.map(x=>`${x}g`)))}</div><div><b>Flexes</b>${esc(list(d.flexes))}</div><div><b>Launch / Spin</b>${esc(list(d.launch))} / ${esc(list(d.spin))}</div><div><b>Tip / Torque</b>${esc(list(d.tipSizes))} / ${esc(torque(d))}</div><div><b>Availability</b>${esc(list(d.availability))}</div><div><b>ShaftDB</b>${d.recordCount} detailed row${d.recordCount===1?'':'s'}</div></div>`}else{details='<div class="reference-note">Reference family — no detailed ShaftDB record yet. Head and family context will still carry forward to SRT.</div>'}
return `<div class="family-card" data-xref="${esc(r.XRefID)}"><div class="family-top"><div><div class="family-name">${esc(familyName(r.ShaftFamilyID,f))}</div><div class="family-id">${esc(r.ShaftFamilyID)}</div></div><span class="offering-type">${esc(r.OfferingType||'OEM Offering')}</span></div>${mpf}${details}</div>`}
function render(){const h=DATA.heads[headId];if(!h){$('headBadge').textContent='HeadID not found';$('headIdentity').innerHTML=`<div class="empty-adapter">No head record found for <b>${esc(headId||'(missing HeadID)')}</b>.</div>`;$('status').textContent='Open this page from a selected CRG head.';return}$('headBadge').textContent=h.HeadID;$('headIdentity').innerHTML=`<div class="head-summary">${esc(labelHead(h))}</div><div class="head-meta">${esc(h.ClubType||'')} • ${esc(h.ModelCategory||'')} ${h.ReferenceTier?`• ${esc(h.ReferenceTier)}`:''}</div>`;const rows=DATA.xref.filter(r=>r.HeadID===headId);$('offeringCount').textContent=`${rows.length} offering${rows.length===1?'':'s'}`;$('status').textContent=rows.length?'Select a family to carry its context into SRT.':'No OEM shaft offerings are mapped to this HeadID yet.';const order=['Steel','Graphite','Other / Material TBD'];$('groups').innerHTML=order.map(g=>{const rr=rows.filter(r=>materialGroup(r.Material)===g);if(!rr.length)return '';return `<section class="material-group"><h3 class="material-title">${g}<span class="count">${rr.length}</span></h3><div class="family-grid">${rr.map(cardHtml).join('')}</div></section>`}).join('');document.querySelectorAll('.family-card').forEach(el=>el.onclick=()=>{document.querySelectorAll('.family-card').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selected=rows.find(r=>r.XRefID===el.dataset.xref);const f=DATA.families[selected.ShaftFamilyID]||{};$('selectionSummary').textContent=`${materialGroup(selected.Material)} • ${familyName(selected.ShaftFamilyID,f)} • ${selected.OfferingType||'OEM Offering'}`;$('replacementBtn').disabled=false;});}
function replacementUrl(){const base='https://ktgerard.github.io/pwa-srt/';const p=new URLSearchParams({headId,shaftFamilyId:selected.ShaftFamilyID,material:selected.Material||'Unknown',offeringType:selected.OfferingType||''});return `${base}?${p.toString()}`}
$('replacementBtn').onclick=()=>{if(selected)window.open(replacementUrl(),'_blank','noopener')};
Promise.all([fetch('data/oem_shaft_xref.json').then(r=>r.json()),fetch('data/shaft_families.json').then(r=>r.json()),fetch('data/shaft_family_details.json').then(r=>r.json()),fetch('data/head_reference.json').then(r=>r.json())]).then(([xref,families,details,heads])=>{DATA={xref,families,details,heads};render()}).catch(e=>{$('status').textContent=`Unable to load OEM shaft reference data: ${e.message}`});